
# Atividade Integradora

Membros
* Bruno
* Henrique
* Yuri


### Importação das principais bibliotecas que serão utilizadas

In [0]:
import pandas as pd
import numpy as np
import pandas_profiling as pp

### Realização do upload da base de dados no servidor do GitHub e a importação da base através do Google Colab

In [0]:
!git clone -l -s https://github.com/brunocarlin/atividade_integradora.git cloned-repo
%cd cloned-repo
!ls

Cloning into 'cloned-repo'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 0), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
/content/cloned-repo/cloned-repo/cloned-repo
BD_PRE.rar  BD_PRE.xlsx  README.md


In [0]:
### Criação do dataframe utilizando o pandas como bilbioteca de manipulação de bases

In [0]:
df1 = pd.read_excel("BD_PRE.xlsx")

### Avaliando as variáveis para serem incluídas no modelo ou não através do Pandas Profiling

In [0]:
pp.ProfileReport(df1)

In [0]:
df1.describe()

IDTNS       ANO_BASE  ...           PESO            I2
count  1.284110e+05  128411.000000  ...  128411.000000  84441.000000
mean   2.062114e+07    2016.269774  ...       0.999992      1.179806
std    2.192746e+07       1.120365  ...       1.315625      0.384028
min    3.780000e+02    2015.000000  ...       0.015936      1.000000
25%    6.160118e+06    2015.000000  ...       0.180556      1.000000
50%    6.804225e+06    2016.000000  ...       0.601990      1.000000
75%    4.105798e+07    2017.000000  ...       1.348837      1.000000
max    6.203986e+07    2018.000000  ...      10.965368      2.000000

[8 rows x 47 columns]

## Realizar o drop das colunas que não serão utilizadas no modelo (IDTNS,TIPO,OPERADORA,ESTADO,DATA,H0,Q1,Q2,Q3,Q4,Q5,Q7)

 ### As variáveis foram retiradas por possuírem valores categóricos e únicos que não seriam interessantes para análise. Pois, sem variância destas features não agregariam em nada para o modelo.

In [0]:
df1=df1.drop(["IDTNS","TIPO","DATA","H0","Q1","Q2","Q3","Q4","Q6","Q7"],axis=1)

df1.head()

OPERADORA ESTADO  ANO_BASE  Q5  Q8  ...      H2  H2a  I1      PESO   I2
0        OI     RJ      2018   1  44  ...  999998    1   2  1.165414  2.0
1        OI     BA      2018   1  50  ...  999998    6   1  1.911877  1.0
2      VIVO     ES      2018   1  37  ...    1000    1   1  0.695489  1.0
3     CLARO     RR      2018   1  19  ...  999998    2   1  0.054054  1.0
4        OI     ES      2018   1  39  ...  999998    7   1  0.111111  1.0

[5 rows x 42 columns]

### Renomeação da coluna J1 para target facilitando a análise da base

In [0]:
df1 = df1.rename(columns = {'J1':'Target'})

In [0]:
df1.head()

OPERADORA ESTADO  ANO_BASE  Q5  Q8  ...      H2  H2a  I1      PESO   I2
0        OI     RJ      2018   1  44  ...  999998    1   2  1.165414  2.0
1        OI     BA      2018   1  50  ...  999998    6   1  1.911877  1.0
2      VIVO     ES      2018   1  37  ...    1000    1   1  0.695489  1.0
3     CLARO     RR      2018   1  19  ...  999998    2   1  0.054054  1.0
4        OI     ES      2018   1  39  ...  999998    7   1  0.111111  1.0

[5 rows x 42 columns]

### Realizando a limpeza da base de acordo com o metadados disponibilizada no site do governo. Para cada variável foi feita uma manipulação de dados, no caso abaixo para toda variável em que o valor era 99 foi definida que esta seria missing. 

In [0]:
df2 =  df1.copy()

In [0]:
df2['B1_1'].replace([99], np.NaN,inplace = True)
df2['B1_2'].replace([99], np.NaN,inplace = True)
df2['C1_1'].replace([99], np.NaN,inplace = True)
df2['C1_2'].replace([99], np.NaN,inplace = True)
df2['D2_1'].replace([99], np.NaN,inplace = True)
df2['D2_2'].replace([99], np.NaN,inplace = True)
df2['D2_3'].replace([99], np.NaN,inplace = True)
df2['F5'].replace([99], np.NaN,inplace = True)
df2['F4'].replace([99], np.NaN,inplace = True)
df2['F2'].replace([99], np.NaN,inplace = True)
df2['A5'].replace([99], np.NaN,inplace = True)
df2['A4'].replace([99], np.NaN,inplace = True)
df2['A3'].replace([99], np.NaN,inplace = True)
df2['A2_1'].replace([99], np.NaN,inplace = True)
df2['A2_2'].replace([99], np.NaN,inplace = True)
df2['A2_3'].replace([99], np.NaN,inplace = True)
df2['E1_1'].replace([99], np.NaN,inplace = True)
df2['E1_2'].replace([99], np.NaN,inplace = True)
df2['E1_3'].replace([99], np.NaN,inplace = True)
df2['F4'].replace([99], np.NaN,inplace = True)
df2['F5'].replace([99], np.NaN,inplace = True)
df2['F6'].replace([99], np.NaN,inplace = True)

### Mesmo caso anterior, porém para os outros casos de valores considerados como missing.

In [0]:
df2['Q8'].replace([999999], np.NaN,inplace = True)
df2['H1'].replace([99,99999], np.NaN,inplace = True)
df2['H2'].replace([99997,99998,99999,100000,999998,999999], np.NaN,inplace = True)

### A feature H2a foi removida, pois logo após seria criada um novo range de valores de salários nomeada como RIQUEZA

In [0]:
df2.drop(["H2a"],inplace = True,axis = 1)

In [0]:
df3 = df2.copy()

In [0]:
df3.loc[(df3["H2"] >=0) & (df3["H2"] <1000), "RIQUEZA"]=1
df3.loc[(df3["H2"] >=1000) & (df3["H2"] <3000), "RIQUEZA"]=2
df3.loc[(df3["H2"] >=3000) & (df3["H2"] <6000), "RIQUEZA"]=3
df3.loc[(df3["H2"] >=6000) & (df3["H2"] <10000), "RIQUEZA"]=4
df3.loc[(df3["H2"] >=10000) & (df3["H2"] <15000), "RIQUEZA"]=5
df3.loc[(df3["H2"] >=15000) & (df3["H2"] <20000), "RIQUEZA"]=6
df3.loc[(df3["H2"] >=20000), "RIQUEZA"]=7

In [0]:
df3.RIQUEZA.value_counts(dropna =False)

2.0    48387
1.0    33554
NaN    29784
3.0    12543
4.0     2704
5.0      850
7.0      315
6.0      274
Name: RIQUEZA, dtype: int64

### No código abaixo, foi definida para os valores de 99 para a Target e logo após todas as linhas que continha Target iguais a missing foram removidas da análise. Além disso, foi criada uma nova variável Target2 definindo se a nota da operadora foi RUIM (0) ou se a nota foi BOA (1).

In [0]:
df3['Target'].replace([99], np.NaN,inplace = True)

df3.loc[(df3["Target"] <=8) ,"Target2"]= 0
df3.loc[(df3["Target"] >8 ) ,"Target2"]= 1


df3.dropna(subset=['Target'],inplace = True)


In [0]:
df3.describe()

ANO_BASE             Q5  ...       RIQUEZA        Target2
count  128198.000000  128198.000000  ...  98524.000000  128198.000000
mean     2016.269450       1.029447  ...      1.895223       0.287391
std         1.120052       0.169055  ...      0.876366       0.452547
min      2015.000000       1.000000  ...      1.000000       0.000000
25%      2015.000000       1.000000  ...      1.000000       0.000000
50%      2016.000000       1.000000  ...      2.000000       0.000000
75%      2017.000000       1.000000  ...      2.000000       1.000000
max      2018.000000       2.000000  ...      7.000000       1.000000

[8 rows x 41 columns]

Variaveis Categoricas Moda
Estado  
Operadora  
RIQUEZA  
Q9  
I1 
D1     
Q5    
F1
F3  
F5  
G1

Variaveis Categoricas Missing Explicito
A1_x



### No código abaixo identificamos que existiam features em que caso o valor estivesse como missing ele representava igual a 0.

In [0]:
df3["A1_1"].fillna(0,inplace = True)
df3["A1_2"].fillna(0,inplace = True)
df3["A1_3"].fillna(0,inplace = True)
df3["A1_4"].fillna(0,inplace = True)
df3["F1"].fillna(0,inplace = True)
df3["F3"].fillna(0,inplace = True)
df3["F5"].fillna(0,inplace = True)

### Após a correção de todos os valores da base, o código abaixo definiu no dataframe se todas as variáveis que seriam categóricas.

In [0]:
df3['Q9'] = df3['Q9'].astype('category')
df3['I1'] = df3['I1'].astype('category')
df3['D1'] = df3['D1'].astype('category')
df3['Q5'] = df3['Q5'].astype('category')
df3['F1'] = df3['F1'].astype('category')
df3['F3'] = df3['F3'].astype('category')
df3['F5'] = df3['F5'].astype('category')
df3['G1'] = df3['G1'].astype('category')
df3["A1_1"] =  df3['A1_1'].astype('category')
df3["A1_2"] =  df3['A1_2'].astype('category')
df3["A1_3"] =  df3['A1_3'].astype('category')
df3["A1_4"] =  df3['A1_4'].astype('category')
df3["RIQUEZA"] =  df3['RIQUEZA'].astype('category')
df3["Target2"] =  df3['Target2'].astype('category')

SyntaxError: ignored

In [0]:
df3.dtypes

OPERADORA     object
ESTADO        object
ANO_BASE       int64
Q5             int64
Q8           float64
Q8a            int64
Q9             int64
Target       float64
B1_1         float64
B1_2         float64
C1_1         float64
C1_2         float64
D1             int64
D2_1         float64
D2_2         float64
D2_3         float64
E1_1         float64
E1_2         float64
E1_3         float64
A1_1         float64
A1_2         float64
A1_3         float64
A1_4         float64
A2_1         float64
A2_2         float64
A2_3         float64
A3           float64
A4           float64
A5           float64
F1             int64
F2           float64
F3             int64
F4           float64
F5           float64
F6           float64
G1             int64
H1           float64
H2           float64
I1             int64
PESO         float64
I2           float64
RIQUEZA      float64
Target2      float64
dtype: object

## Realizar a importação dos modelos que serão utilizados

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Inicio da Modelagem

## Separação da base de dados em features e Target

In [0]:
# Para as variáveis que dependiam da resposta de outras, estas foram retiradas da análise. Desta forma, foram apenas contempladas as variáveis que seja indepedentes de outras.
df4=df3.loc[:,['Q5','Q8','Q8a','Q9','B1_1','B1_2','C1_1','C1_2','D1','D2_1','D2_2','D2_3','E1_1','E1_2','E1_3','A1_1','A1_2','A1_3','A1_4','F1','F3','F5','G1','H1','I1','PESO','RIQUEZA',"Target2"]]
df4=df4.dropna()

In [0]:
X = df4.loc[:, df4.columns != 'Target2']
y = df4.loc[:,["Target2"]]

In [0]:
X

Q5    Q8  Q8a  Q9  B1_1  B1_2  ...   F5  G1   H1  I1      PESO  RIQUEZA
2        1  37.0    6   1   9.0  10.0  ...  2.0   2  1.0   1  0.695489      2.0
5        1  38.0    6   2  10.0  10.0  ...  2.0   2  5.0   1  0.111111      1.0
8        1  22.0    3   2  10.0   9.0  ...  2.0   2  2.0   2  0.590517      2.0
9        1  27.0    4   2   4.0   6.0  ...  1.0   1  1.0   1  0.504950      2.0
14       1  40.0    6   1  10.0  10.0  ...  1.0   1  2.0   1  2.985577      2.0
15       2  18.0    3   1   5.0  10.0  ...  2.0   1  2.0   1  0.695489      2.0
19       1  38.0    6   2   7.0   7.0  ...  2.0   1  2.0   2  0.076923      4.0
21       1  22.0    3   1   8.0  10.0  ...  2.0   1  2.0   2  0.617778      2.0
22       1  37.0    6   2   5.0   8.0  ...  2.0   1  2.0   1  0.111111      4.0
23       1  20.0    3   1   6.0   3.0  ...  2.0   1  2.0   1  0.814433      2.0
27       1  36.0    6   2  10.0  10.0  ...  2.0   1  1.0   2  0.915966      2.0
30       1  30.0    4   2   2.0   1.0  ...  1.0   1  1.0   2  0.926108      3.0
32       1  22.0    3   1  10.0   9.0  ...  2.0   2  2.0   2  0.100529      1.0
35       2  25.0    4   2  10.0   8.0  ...  2.0   2  2.0   1  1.174888      2.0
38       1  36.0    6   1   8.0   8.0  ...  2.0   1  2.0   2  0.551724      2.0
39       1  19.0    3   2   8.0  10.0  ...  2.0   1  3.0   1  0.504950      2.0
40       1  41.0    7   2   5.0   4.0  ...  2.0   1  2.0   1  0.075949      1.0
42       1  39.0    6   2   0.0   0.0  ...  2.0   1  2.0   1  0.551724      4.0
43       1  20.0    3   2   9.0   8.0  ...  2.0   1  3.0   1  2.985577      1.0
46       1  24.0    3   2   8.0   7.0  ...  1.0   1  4.0   1  0.702381      7.0
47       1  42.0    7   2   7.0  10.0  ...  2.0   1  1.0   2  0.581028      1.0
48       1  48.0    7   1   6.0   6.0  ...  2.0   1  2.0   2  0.852941      2.0
51       1  26.0    4   2   9.0  10.0  ...  2.0   1  1.0   1  0.549180      2.0
53       1  62.0    8   1   8.0   8.0  ...  2.0   1  2.0   1  1.004464      3.0
56       1  43.0    7   2  10.0  10.0  ...  2.0   1  5.0   1  0.100529      3.0
58       1  25.0    4   1   0.0   3.0  ...  2.0   2  3.0   1  0.551724      2.0
60       1  28.0    4   2   8.0   8.0  ...  2.0   3  1.0   1  0.607306      3.0
62       1  22.0    3   1   7.0  10.0  ...  2.0   2  1.0   1  0.050000      2.0
64       1  32.0    5   1   7.0  10.0  ...  2.0   1  1.0   1  2.310881      1.0
65       1  58.0    8   2  10.0   5.0  ...  2.0   1  1.0   2  1.165414      4.0
...     ..   ...  ...  ..   ...   ...  ...  ...  ..  ...  ..       ...      ...
128330   2  34.0    5   1   9.0   9.0  ...  2.0   1  1.0   2  0.020290      2.0
128335   1  32.0    5   2   8.0   8.0  ...  2.0   1  2.0   1  0.268293      2.0
128337   1  32.0    5   1   8.0  10.0  ...  2.0   1  2.0   1  0.020290      2.0
128338   1  29.0    4   1   7.0   8.0  ...  1.0   1  2.0   1  0.020290      3.0
128340   1  21.0    3   1  10.0   8.0  ...  2.0   2  2.0   2  0.268293      1.0
128341   1  31.0    5   1  10.0   8.0  ...  2.0   2  4.0   2  0.268293      2.0
128346   1  28.0    4   1   5.0   7.0  ...  2.0   2  3.0   1  0.020290      1.0
128348   1  23.0    3   2   7.0   6.0  ...  2.0   1  1.0   1  0.171271      1.0
128349   1  42.0    7   2  10.0  10.0  ...  2.0   2  2.0   2  0.571809      2.0
128350   1  26.0    4   1   5.0   8.0  ...  2.0   2  1.0   2  0.571809      2.0
128351   1  33.0    5   1  10.0  10.0  ...  1.0   1  3.0   2  0.571809      1.0
128356   1  30.0    4   1   9.0   7.0  ...  2.0   1  3.0   1  0.571809      1.0
128357   1  21.0    3   1   7.0   7.0  ...  1.0   2  2.0   1  0.571809      1.0
128358   1  46.0    7   2   6.0   5.0  ...  2.0   1  2.0   1  0.571809      2.0
128360   1  21.0    3   1   8.0   9.0  ...  2.0   1  3.0   1  0.268293      2.0
128361   1  22.0    3   1   5.0   5.0  ...  1.0   1  4.0   1  0.268293      1.0
128365   1  34.0    5   2   8.0   7.0  ...  2.0   2  4.0   2  0.268293      3.0
128368   1  32.0    5   1   9.0   7.0  ...  1.0   1  3.0   1  0.020290      1.0
128369  

In [0]:
X = pd.get_dummies(X,drop_first = True)

## Criacao de base de treino e teste

In [0]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size = 0.2, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

y_train= y_train.values.ravel()
y_test= y_test.values.ravel()

## Modelo 1 - Classificação Regressão Logística

In [0]:
lm_regressor=LogisticRegression()
lm_regressor.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred=lm_regressor.predict(X_test)
print(y_pred)

[0. 0. 0. ... 1. 0. 0.]


#### Cross_val_score é uma função do ScikitLearn para evitar o overfiting (K-folds)

In [0]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lm_regressor, X_train,y_train,
scoring="accuracy", cv=5)
scores.mean()

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur

0.8426057048023319

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8427539720751084

## Modelo 2 - Classificação Vizinhos Mais próximos

In [0]:
knn_regressor=KNeighborsClassifier()
knn_regressor.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred=knn_regressor.predict(X_test)
print(y_pred)

[0. 1. 0. ... 0. 1. 0.]


#### Cross_val_score é uma função do ScikitLearn para evitar o overfiting (K-folds)

In [0]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn_regressor, X_train,y_train,
scoring="accuracy", cv=5)
scores.mean()

0.8152336617220286

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8114588348579682

## Modelo 3 - Classificação com árvore de decisão

In [0]:
dt_regressor=DecisionTreeClassifier()
dt_regressor.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [0]:
y_pred=dt_regressor.predict(X_test)
print(y_pred)

[0. 1. 1. ... 1. 1. 0.]


#### Cross_val_score é uma função do ScikitLearn para evitar o overfiting (K-folds)

In [0]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dt_regressor, X_train,y_train,
scoring="accuracy", cv=5)
scores.mean()

0.7743324466218401

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7714973519499277

## Modelo 4 - Classificação com Random Forest

In [0]:
rf_regressor=RandomForestClassifier()
rf_regressor.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
y_pred=rf_regressor.predict(X_test)
print(y_pred)

[0. 0. 0. ... 1. 0. 0.]


#### Cross_val_score é uma função do ScikitLearn para evitar o overfiting (K-folds)

In [0]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(rf_regressor, X_train,y_train,
scoring="accuracy", cv=5)
scores.mean()

0.8326150790566558

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8311025517573423

# Conclusão
 
## Resultados dos modelos
 * Modelo 1 - Regressão Logística (Acurácia = 0.8427539720751084 )
 * Modelo 2 - KNN (Acurácia = 0.8114588348579682)
 * Modelo 3 - Árvore de Decisão (Acurácia = 0.7714973519499277)
 * Modelo 4 - Random Forest (Acurácia = 0.8311025517573423)
 
## Dado a métrica de acurácia o melhor modelo é o Modelo 1 - Regressão Logística